### ISSUE TITLE
Alpha sorting of the boards

### ISSUE THREAD

**Issue by fede2cr** [adafruit/Adafruit_Python_PlatformDetect#158]
While working on adding a couple of the riscv boards, I noted that the boards could use a bit of sorting to make it easier to edit.

Is it ok if I PR the coded with the chips+boards sorted out?

**Comment by makermelissa** [comment]
Are you referring to the detection code or the constants? If the constants, please leave them in their related board families and maybe sort the families alphabetically. If the detection code, it kind of needs to be in the order it is in. Thanks.

**Comment by makermelissa** [comment]
Closing due to lack of response. If you want to submit a PR that keeps the board types grouped in families, I'm ok with that.
