### ISSUE TITLE
Board not supported {}".format(board_id) needs better error message.  

### ISSUE THREAD

**Issue by arhyneRWU** [adafruit/Adafruit_Python_PlatformDetect#167]
This will become a more common error as newer hardware is used on older images or packages.  It's a nonintuitive issue, as board.py is the same as several scripts. 

`import adafruit_motorkit File "/usr/local/lib/python3.7/dist-packages/adafruit_motorkit.py", line 55, in <module> import board **File "/home/pi/.local/lib/python3.7/site-packages/board.py", line 166, in <module> raise **NotImplementedError("Board not supported {}".format(board_id)) NotImplementedError: Board not supported None**`**

The error message should instruct the user that their hardware is unknown to the version of platformdetect (give version) , to upgrade to the latest version using:  _pip3 install --upgrade adafruit-blinka adafruit-platformdetect_

**Comment by makermelissa** [comment]
Great idea. Want to submit a Pull Request?

**Comment by arhyneRWU** [comment]
Yea, be happy to.  I'll have to look at the code and get that set up.

**Comment by makermelissa** [comment]
Thank you

**Comment by ryanddunn** [comment]
I'm not that familiar with Python, Adafruit, etc. so please forgive my ignorance. I'm running into this exact error. 

I ran the command... 

`pip3 install --upgrade adafruit-blinka adafruit-platformdetect`

But that didn't see to help my issue. Here is the full error I'm running into. 

```
Traceback (most recent call last):
  File "/media/ryan/RPI-RP2/code.py", line 2, in <module>
    import board
  File "/home/ryan/PycharmProjects/MacroPad-RP2040/venv/lib/python3.10/site-packages/board.py", line 279, in <module>
    raise NotImplementedError("Board not supported {}".format(board_id))
NotImplementedError: Board not supported GENERIC_LINUX_PC

Process finished with exit code 1
```
FYI, Ubuntu 22 LTS, PyCharm, Python 3.10.4

Any ideas?

**Comment by arhyneRWU** [comment]
Please provide your board name.  Your running what type of microcomputer?  Is it a PC running Linux?

The error is generated because your board is not found.  

The code is erroring because it's trying to import the board pin configurations but can't find your model. 

error is here
https://github.com/adafruit/Adafruit_Blinka/blob/main/src/board.py

can't find a board so gets to else:
```
else:
    raise NotImplementedError("Board not supported {}".format(board_id))
```

Needs your pin names that are found in this directory and has to import that board in the code above. 
https://github.com/adafruit/Adafruit_Blinka/tree/main/src/adafruit_blinka/board

**Comment by ryanddunn** [comment]
Thank you for the reply @arhyneRWU 

I believe the board name is "MacroPad RP2040" (Raspberry Pi RP2040 Chip) <https://circuitpython.org/board/adafruit_macropad_rp2040/>

Connecting to Linux, specifically Ubuntu 22.04 LTS
