### ISSUE TITLE
JETSON_NANO is capitalized

### ISSUE THREAD

**Issue by robomike** [adafruit/Adafruit_Python_PlatformDetect#169]
The nomenclature is supposed to be all lowercase to be consistent with pulseio board detection.  However, this is the result:

'>>> detector.board.id
'JETSON_NANO'
detector.board.jetson_nano
False
>>> detector.board.jetson_nx
False
>>> detector.board.JETSON_NANO
True

Which breaks all files in Blinka looking for lowercase

**Comment by makermelissa** [comment]
All boards are uppercase. Currently pulseio is looking at these properties: https://github.com/adafruit/Adafruit_Python_PlatformDetect/blob/master/adafruit_platformdetect/board.py#L462-L622

**Comment by robomike** [comment]
I added this code to pulseio.py on a development versions, all of the names are lower case in the file.  however the only thing that worked for the jetson was this capital line:

`elif detector.board.JETSON_NANO:`

**Comment by robomike** [comment]
Ping.  Can you please explain why all the elif in the blinka pulseio.py is lower case if detector is supposed to be capitalized?  I'd like to finish the pulseio implementation

**Comment by dhalbert** [comment]
> I added this code to pulseio.py on a development versions, all of the names are lower case in the file. however the only thing that worked for the jetson was this capital line:
> 
> `elif detector.board.JETSON_NANO:`

This will always be true, because it's a constant that is "truthy":

> Can you please explain why all the elif in the blinka pulseio.py is lower case if detector is supposed to be capitalized

It is just a name for the string. In `detector/constants/boards.py`, there is this: `JETSON_NANO = "JETSON_NANO"`. The `if` in blinka pulseio.py is actually checking whether a certain kind of board is present. For Jetson, you want to check:
```py
elif detector.board.any_jetson_board:
...
```
That will return true if it's a Jetson board.

**Comment by makermelissa** [comment]
@dhalbert explained this well. You may also consider using something like:
```
if detector.board.id == detector.board.JETSON_NANO:
```

**Comment by makermelissa** [comment]
Closing because making this change would break a lot of other stuff.
