### ISSUE TITLE
Duplicate constants in boards and chips

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/Adafruit_Python_PlatformDetect#174]
I'm trying to get `pre-commit` working to close #140.

However `pre-commit` fails locally on `pylint` with
```
adafruit_platformdetect/board.py:1:0: R0801: Similar lines in 2 files
==adafruit_platformdetect.constants.boards:119
==adafruit_platformdetect.constants.chips:48
PICO_U2IF = "PICO_U2IF"
FEATHER_U2IF = "FEATHER_U2IF"
ITSYBITSY_U2IF = "ITSYBITSY_U2IF"
QTPY_U2IF = "QTPY_U2IF"
QT2040_TRINKEY_U2IF = "QT2040_TRINKEY_U2IF"
 (duplicate-code)
```
This is detected in the `build.yml` Github action but seems to pass anyway, for example https://github.com/adafruit/Adafruit_Python_PlatformDetect/runs/2797662229?check_suite_focus=true under the Pylint section

Do these need to be defined in both files?

**Comment by makermelissa** [comment]
I think they do both need to be there. You could always re-arrange them since they're constants, the order doesn't matter too much.
