### ISSUE TITLE
chip.py returns true for similar strings

### ISSUE THREAD

**Issue by twa127** [adafruit/Adafruit_Python_PlatformDetect#178]
Hi,

In chip.py the python operator 'in' is used for chip detection, but this can cause problems for similar strings e.g.

if self.detector.check_dt_compatible_value("sun50i-h6"): and if self.detector.check_dt_compatible_value("sun50i-h616"): will both be true.

**Comment by makermelissa** [comment]
Good point. h616 should be checked before h6

**Comment by twa127** [comment]
yeah that will do it, shall I commit an update?

**Comment by makermelissa** [comment]
Please and thank you.

**Comment by twa127** [comment]
okay done :-)

**Comment by makermelissa** [comment]
Thank you!
