### ISSUE TITLE
Add support for Allwinner D1?

### ISSUE THREAD

**Issue by modi12jin** [adafruit/Adafruit_Python_PlatformDetect#181]
![image-20210326092730292](https://user-images.githubusercontent.com/40233017/124281800-b1c77a80-db7c-11eb-892f-f45accc50cca.png)

![image-20210508170547006](https://user-images.githubusercontent.com/40233017/124281812-b4c26b00-db7c-11eb-9362-29837c761f18.png)

> Allwinner online developer community

```
https://www.aw-ol.com/
```

![image](https://user-images.githubusercontent.com/40233017/124282031-ecc9ae00-db7c-11eb-8978-03feadce3e35.png)

**Comment by makermelissa** [comment]
https://learn.adafruit.com/adding-a-single-board-computer-to-platformdetect-for-blinka
