### ISSUE TITLE
add support for Raspberry Pi CM4 8G ram version

### ISSUE THREAD

**Issue by Sheng2216** [adafruit/Adafruit_Python_PlatformDetect#240]
the current version cannot identify the 8G ram version of Raspberry Pi CM4, please consider adding it
https://github.com/adafruit/Adafruit_Python_PlatformDetect/blob/2da28d30c53f655652d146a0cabb64eeac389d33/adafruit_platformdetect/constants/boards.py#L492

only need to add  "d03141" to the list:

RASPBERRY_PI_CM4: ("a03140", "b03140", "c03140", "d03140", “d03141”),

**Comment by ladyada** [comment]
please submit a PR if you have the hardware - thats the best way:)
