### ISSUE TITLE
Simplify Pi 4 (and possibly CM4) Rev Code Checks

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_Python_PlatformDetect#268]
See #262 for more details. Essentially, it's possible to have variations on the base rev code and instead of having a list of every possible permutation, it might be better to have it check it more intelligently.

**Comment by KmakD** [comment]
Is there an update on this issue? Do you plan to work on it in the nearest feature?

**Comment by makermelissa** [comment]
Hi, no update currently because I've been focusing on web work. I might take a break and work on this soon. It should be fairly easy to knock out.
