### ISSUE TITLE
a03111 and b03111 missing from Pi 4 board revision codes

### ISSUE THREAD

**Issue by garyexplains** [adafruit/Adafruit_Python_PlatformDetect#29]
While c03111 has been added (the 4GB) version. The 1GB and 2GB version have different revision codes.

**Comment by ladyada** [comment]
huh we tested on our 2GB - dont have a 1 or 4 - do you know those codes and can you add them as a PR?

**Comment by garyexplains** [comment]
The codes are what I listed in the subject. I got them from the revision
code document on the Raspberry Pi website, the one mentioned in the script.

**Comment by ladyada** [comment]
great - can you add them as a PR?

**Comment by makermelissa** [comment]
Interestingly enough, I just checked my 2GB model and it's showing a Rev code of `b03111`.

**Comment by ladyada** [comment]
oh yeah sorry i had an early release 4gb

**Comment by makermelissa** [comment]
Makes sense. :)
